export { EfficiencyPage } from '../../components/platform/Efficiency'
export { PlaybooksPage } from '../../components/platform/Playbooks'
export { ReportsPage } from '../../components/platform/Reports'
export { FormatPacksPage } from '../../components/platform/FormatPacks'
export { IntegrationsPage } from '../../components/platform/Integrations'
export { AdminPage } from '../../components/platform/Admin'
